name: Pull from Repo

on:
  push:
    branches:
      - main  

jobs:
  pull:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull changes from server
        run: |
          git remote add server https://github.com/Andrew-Dupere/demotraders.git
          git fetch server
          git merge server/main

      
      - name: Push changes to server
        run: |
          git push origin main  

