name: Pull from Repo

on:
  push:
    branches:
      - main 

env:
  AWS_DEFAULT_REGION: us-east-1 

jobs:
  pull:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Pull changes from server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@18.117.180.117 "cd /home/ubuntu/kezan/apps/demotraders && git pull origin main"
