name: Pull from Repo

on:
  push:
    branches:
      - main 

env:
  AWS_DEFAULT_REGION: us-east-1 

jobs:
  pull:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull changes from server
        run: |
          ssh ubuntu@your-server-ip "cd /path/to/your/repository && git pull origin main"
